### ISSUE TITLE
TypeError: new Canvacord.Rank() is not a constructor

### ISSUE THREAD

**Issue by hakimnul47** [archaeopteryx1/canvacord#139]
Also i've tried npm i discord-canvas but an error in my terminal

**Comment by archaeopteryx1** [comment]
discord-canvas is no longer needed on the latest version. Also, this error might be due to improper import done by you.

The import should roughly look like this:

```js
const Canvacord = require("canvacord");

const card = new Canvacord.Rank();

// or just
const { Rank } = require("canvacord");

const card = new Rank();
```
